final List<Map<String, dynamic>> products = [
  {
    'category': 'Sneakers',
    'title': 'Nike Air Max 200',
    'description': 'Perfect for cold weather.',
    'rating': 4.2,
    'price': 240.0,
    'imageUrl': 'images/shose.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Sneakers',
    'title': 'Mesh',
    'description': 'Perfect for cold weather.',
    'rating': 4.2,
    'price': 240.0,
    'imageUrl': 'images/mesh.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Sneakers',
    'title': 'Canvas',
    'price': 280.0,
    'imageUrl': 'images/Canvas.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Sneakers',
    'title': 'Cork',
    'description': 'Perfect for cold weather.',
    'rating': 4.2,
    'price': 240.0,
    'imageUrl': 'images/cort.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Sneakers',
    'title': 'sport',
    'description': 'Perfect for cold weather.',
    'rating': 4.2,
    'price': 240.0,
    'imageUrl': 'images/leather shose.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Sneakers',
    'title': 'Cotton',
    'description': 'Perfect for cold weather.',
    'rating': 4.2,
    'price': 220.0,
    'imageUrl': 'images/cotton 2.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Sneakers',
    'title': 'Cotton',
    'description': 'Perfect for cold weather.',
    'rating': 4.2,
    'price': 220.0,
    'imageUrl': 'images/nnike.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Sneakers',
    'title': 'Nike',
    'description': 'Perfect for cold weather.',
    'rating': 4.2,
    'price': 220.0,
    'imageUrl': 'images/cotton.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Sneakers',
    'title': 'Nike',
    'description': 'Perfect for cold weather.',
    'rating': 4.2,
    'price': 220.0,
    'imageUrl': 'images/nike2.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Sneakers',
    'title': 'Cotton',
    'description': 'Perfect for cold weather.',
    'rating': 4.2,
    'price': 220.0,
    'imageUrl': 'images/nike shose.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Jacket',
    'title': 'White Jacket',
    'description': 'Perfect for cold weather.',
    'rating': 4.2,
    'price': 150.0,
    'imageUrl': 'images/winter.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Jacket',
    'title': 'Baby Pink Jacket',
    'description': 'Perfect for cold weather.',
    'rating': 4.2,
    'price': 180.0,
    'imageUrl': 'images/leather.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Jacket',
    'title': 'Dark Rose Jacket',
    'description': 'Perfect for cold weather.',
    'rating': 4.2,
    'price': 180.0,
    'imageUrl': 'images/denim.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Jacket',
    'title': 'Leather Jacket',
    'description': 'Perfect for cold weather.',
    'rating': 4.2,
    'price': 140.0,
    'imageUrl': 'images/raincoat1.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Jacket',
    'title': 'Blazer',
    'description': 'Perfect for cold weather.',
    'rating': 4.7,
    'price': 190.0,
    'imageUrl': 'images/blazer.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Jacket',
    'title': 'Pink Suite',
    'description': 'Perfect for cold weather.',
    'rating': 4.2,
    'price': 180.0,
    'imageUrl': 'images/Trenchcoat.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Jacket',
    'title': 'Red Orange Blazer',
    'description': 'Perfect for cold weather.',
    'rating': 4.2,
    'price': 180.0,
    'imageUrl': 'images/trench coat.jpg',
    'count_of_product': 10,
  },

  {
    'category': 'Watch',
    'title': 'White Gold Watch',
    'description': 'Perfect for cold weather.',
    'rating': 4.2,
    'price': 500.0,
    'imageUrl': 'images/w2.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Watch',
    'title': 'Silver Gold Watch',
    'description': 'Perfect for cold weather.',
    'rating': 3.2,
    'price': 120.0,
    'imageUrl': 'images/rolx.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Watch',
    'title': 'Gold Watch',
    'description': 'Perfect for cold weather.',
    'rating': 4.2,
    'price': 120.0,
    'imageUrl': 'images/aviator.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Watch',
    'title': 'Black Gold Watch',
    'price': 160.0,
    'description': 'Perfect for cold weather.',
    'rating': 2.2,
    'imageUrl': 'images/smart Watch.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Watch',
    'title': 'Silver Gold Watch',
    'description': 'Perfect for cold weather.',
    'rating': 4.2,
    'price': 120.0,
    'imageUrl': 'images/digital.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Watch',
    'title': 'Gold Watch',
    'description': 'Perfect for cold weather.',
    'rating': 4.2,
    'price': 120.0,
    'imageUrl': 'images/Quartz.jpg',
    'count_of_product': 10,
  },
  {
    'category': 'Watch',
    'title': 'Gold Watch',
    'description': 'Perfect for cold weather.',
    'rating': 4.2,
    'price': 120.0,
    'imageUrl': 'images/casio.jpg',
    'count_of_product': 10,
  },
];
